version: '3.8'
services:
  snmpwalker:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: snmpwalker  
    environment:
      - SNMP_VERSION=2c
      - MIBS=ALL
      - COMMUNITY=intelbras123
      - HOST=10.100.73.249
      - VENDORID=SNMPv2-SMI::enterprises.26138
      - OUTPUT_FILE=/out/snmpwalk-10.100.73.249.txt
    volumes:
      - ./out:/out
      - ./libs:/usr/share/snmp/mibs
  formatter: 
    image: python:alpine3.15
    container_name: formatter
    volumes:
      - ./out:/out
      - ./scripts:/scripts
    environment:
      - INPUT_FOLDER=/out
    command: sh -c "python3 /scripts/formatter.py"