version: '3.8'
services:
  snmpwalker:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: snmpwalker  
    env_file:
      - ./env/.env_example
    volumes:
      - ./out:/out
      - ./libs:/usr/share/snmp/mibs
  formatter: 
    image: python:alpine3.15
    container_name: formatter
    volumes:
      - ./out:/out
      - ./scripts:/scripts
    environment:
      - INPUT_FILE=/out/snmpwalk.txt
    command: sh -c "python3 /scripts/formatter.py"