version: '3.8'
services:
  snmpwalker:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: snmpwalker  
    env_file:
      - ./env/.env_example
    volumes:
      - ./out:/out
      - ./libs:/usr/share/snmp/mibs