version: '3.8'
services:
  snmpwalker:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: snmpwalker
    environment:
      SNMP_VERSION: "2c"
      MIBS: "ALL"
      COMMUNITY: "intelbras123"
      HOST: "10.100.73.249"
      OID: "SNMPv2-SMI::enterprises.26138"
    volumes:
      - ./out:/out
      - ./libs:/usr/share/snmp/mibs